### ISSUE TITLE
How to start expanded?

### ISSUE THREAD

**Issue by arvanus** [apptreesoftware/flutter_calendar#17]
How to start expanded?
I want to use isExpandable: false, and start with the calendar expanded, I can easily change line 44 from flutter_calendar from   
`bool isExpanded = false;`
to 
`  bool isExpanded = true;`
But it will work until next update... 
Any idea?
Can I add an constructor and commit it too?
Thanks

**Comment by ericwindmill** [comment]
This issue is fixed, expansion should work as expected.

**Comment by markdevise** [comment]
I still cannot get the calendar to start as expanded. Currently on version 0.0.7.
